# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13818483b6815088055b2483e680f4748e39047a2b952b62e2de244e310708ee461ae31c87808f0b6dbd7ea9917f3b133a2ddbdf69a5e85ec0ea210e1c8ff874

test:
  secret_key_base: 26dfaa56f9f4ef5f0cc56a824c078906275858c9b2bc8f7a926df79629a99c529f408b6895bff01c61df9636faed72ab68da51de2a49c2adb2bd9a358a088523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
