# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d22d7858aabb7a23321bd69e9588f8dbaa791d4f89d2da7e2f0c7e4f7a8fb8625007bcb1e4b70146d37b7d6d708cbdf2ba03d84509208bd588c2f33688eacb

test:
  secret_key_base: 5fd9c3304c2ab53b6e5510063266f959635233fed0e2efbbbcbbd0481be66525910c153cd32817f8818c22e22859342edf9b44d201f589557d1bb3bf7233d5b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
